[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
bcrypt = "0.17.0"
bson = "2.15.0"
chrono = "0.4.41"
dotenvy = "0.15.7"
jsonwebtoken = "9.3.1"
mongodb = "3.2.4"
serde = "1.0.219"
serde_json = "1.0.142"
tokio = "1.47.1"
